#import <Cocoa/Cocoa.h>
#import <WebKit/WebKit.h>

@interface AppDelegate : NSObject <NSApplicationDelegate, NSWindowDelegate>
@property NSWindow *window;
@property WKWebView *webView;
@property NSTextField *statusLabel;
@property NSTask *streamlitTask;
@property NSTask *ollamaTask;
@property NSFileHandle *logHandle;
@property NSString *projectPath;
@property BOOL ownsStreamlit;
@end

@implementation AppDelegate
- (void)log:(NSString *)message { NSString *line=[NSString stringWithFormat:@"%@ %@\n",[NSDate date],message]; @try {[self.logHandle seekToEndOfFile];[self.logHandle writeData:[line dataUsingEncoding:NSUTF8StringEncoding]];} @catch (__unused NSException *e) {} }
- (void)prepareLog { NSString *folder=[NSHomeDirectory() stringByAppendingPathComponent:@"Library/Logs/AI Search"]; [[NSFileManager defaultManager] createDirectoryAtPath:folder withIntermediateDirectories:YES attributes:nil error:nil]; NSString *path=[folder stringByAppendingPathComponent:@"AI Search.log"]; if(![[NSFileManager defaultManager] fileExistsAtPath:path])[[NSData data] writeToFile:path atomically:YES]; self.logHandle=[NSFileHandle fileHandleForWritingAtPath:path]; }
- (void)showError:(NSString *)message { [self log:message]; dispatch_async(dispatch_get_main_queue(),^{NSAlert *alert=[[NSAlert alloc]init];alert.messageText=@"AI Search nelze spustit";alert.informativeText=message;alert.alertStyle=NSAlertStyleCritical;[alert addButtonWithTitle:@"OK"];[alert runModal];[NSApp terminate:nil];}); }
- (BOOL)serviceReady:(NSString *)urlString { NSMutableURLRequest *request=[NSMutableURLRequest requestWithURL:[NSURL URLWithString:urlString]];request.timeoutInterval=.7;NSHTTPURLResponse *response=nil;NSError *error=nil;[NSURLConnection sendSynchronousRequest:request returningResponse:&response error:&error];return error==nil&&response.statusCode>=200&&response.statusCode<500; }
- (NSString *)executableFromCandidates:(NSArray<NSString *> *)candidates { for(NSString *path in candidates)if([[NSFileManager defaultManager]isExecutableFileAtPath:path])return path;return nil; }
- (NSTask *)launchTask:(NSString *)path arguments:(NSArray<NSString *> *)arguments name:(NSString *)name { NSTask *task=[[NSTask alloc]init];task.executableURL=[NSURL fileURLWithPath:path];task.arguments=arguments;NSMutableDictionary *environment=[[[NSProcessInfo processInfo]environment]mutableCopy];environment[@"PATH"]=@"/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin";environment[@"BROWSER_GATHER_USAGE_STATS"]=@"false";task.environment=environment;task.currentDirectoryURL=[NSURL fileURLWithPath:self.projectPath];task.standardOutput=self.logHandle;task.standardError=self.logHandle;NSError *error=nil;if(![task launchAndReturnError:&error]){[self log:[NSString stringWithFormat:@"%@ se nepodařilo spustit: %@",name,error.localizedDescription]];return nil;}[self log:[NSString stringWithFormat:@"%@ spuštěn (PID %d)",name,task.processIdentifier]];return task; }
- (void)setupMenu { NSMenu *main=[[NSMenu alloc]init];NSMenuItem *appItem=[[NSMenuItem alloc]init];[main addItem:appItem];NSMenu *appMenu=[[NSMenu alloc]initWithTitle:@"AI Search"];[appMenu addItemWithTitle:@"O AI Search" action:@selector(orderFrontStandardAboutPanel:) keyEquivalent:@""];[appMenu addItem:[NSMenuItem separatorItem]];[appMenu addItemWithTitle:@"Ukončit AI Search" action:@selector(terminate:) keyEquivalent:@"q"];appItem.submenu=appMenu;NSMenuItem *fileItem=[[NSMenuItem alloc]init];[main addItem:fileItem];NSMenu *fileMenu=[[NSMenu alloc]initWithTitle:@"Soubor"];NSMenuItem *reload=[fileMenu addItemWithTitle:@"Obnovit" action:@selector(reloadPage:) keyEquivalent:@"r"];reload.target=self;fileItem.submenu=fileMenu;NSMenuItem *settingsItem=[[NSMenuItem alloc]init];[main addItem:settingsItem];NSMenu *settingsMenu=[[NSMenu alloc]initWithTitle:@"Nastavení"];NSMenuItem *openSettings=[settingsMenu addItemWithTitle:@"Otevřít nastavení" action:@selector(openSettings:) keyEquivalent:@","];openSettings.target=self;settingsItem.submenu=settingsMenu;NSMenuItem *helpItem=[[NSMenuItem alloc]init];[main addItem:helpItem];NSMenu *helpMenu=[[NSMenu alloc]initWithTitle:@"Nápověda"];NSMenuItem *help=[helpMenu addItemWithTitle:@"Nápověda AI Search" action:@selector(showHelp:) keyEquivalent:@"?"];help.target=self;helpItem.submenu=helpMenu;NSApp.mainMenu=main; }
- (void)createWindow { NSRect frame=NSMakeRect(0,0,1500,950);self.window=[[NSWindow alloc]initWithContentRect:frame styleMask:(NSWindowStyleMaskTitled|NSWindowStyleMaskClosable|NSWindowStyleMaskMiniaturizable|NSWindowStyleMaskResizable) backing:NSBackingStoreBuffered defer:NO];self.window.title=@"AI Search";self.window.delegate=self;self.window.minSize=NSMakeSize(900,650);[self.window setFrameAutosaveName:@"AI Search Main Window"];if(![self.window setFrameUsingName:@"AI Search Main Window"])[self.window center];WKWebViewConfiguration *configuration=[[WKWebViewConfiguration alloc]init];self.webView=[[WKWebView alloc]initWithFrame:self.window.contentView.bounds configuration:configuration];self.webView.autoresizingMask=NSViewWidthSizable|NSViewHeightSizable;self.webView.hidden=YES;[self.window.contentView addSubview:self.webView];self.statusLabel=[NSTextField labelWithString:@"Spouštím AI Search…"];self.statusLabel.font=[NSFont systemFontOfSize:18 weight:NSFontWeightMedium];self.statusLabel.alignment=NSTextAlignmentCenter;self.statusLabel.frame=NSMakeRect(100,frame.size.height/2-20,frame.size.width-200,40);self.statusLabel.autoresizingMask=NSViewMinYMargin|NSViewMaxYMargin|NSViewWidthSizable;[self.window.contentView addSubview:self.statusLabel];[self.window makeKeyAndOrderFront:nil]; }
- (void)applicationDidFinishLaunching:(NSNotification *)notification { [self prepareLog];NSString *pathFile=[[NSBundle mainBundle]pathForResource:@"project-path" ofType:@"txt"];self.projectPath=[[[NSString stringWithContentsOfFile:pathFile encoding:NSUTF8StringEncoding error:nil]stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]]stringByStandardizingPath];[self setupMenu];[self createWindow];NSString *iconPath=[[NSBundle mainBundle]pathForResource:@"AI Search" ofType:@"icns"];if(iconPath)NSApp.applicationIconImage=[[NSImage alloc]initWithContentsOfFile:iconPath];NSString *python=[self.projectPath stringByAppendingPathComponent:@".venv/bin/python"];NSString *app=[self.projectPath stringByAppendingPathComponent:@"app.py"];if(![[NSFileManager defaultManager]isExecutableFileAtPath:python]||![[NSFileManager defaultManager]fileExistsAtPath:app]){[self showError:@"Projektové prostředí nebo aplikace nebyly nalezeny. Zkontrolujte instalaci AI Search."];return;}dispatch_async(dispatch_get_global_queue(QOS_CLASS_USER_INITIATED,0),^{if(![self serviceReady:@"http://127.0.0.1:11434/api/tags"]){NSString *ollama=[self executableFromCandidates:@[@"/opt/homebrew/bin/ollama",@"/usr/local/bin/ollama"]];if(ollama)self.ollamaTask=[self launchTask:ollama arguments:@[@"serve"] name:@"Ollama"];else[self log:@"Ollama nebyla nalezena. Vyhledávání bude fungovat bez generování odpovědí."];}else[self log:@"Ollama již běží; launcher ji nebude spravovat."];if(![self serviceReady:@"http://127.0.0.1:8501/_stcore/health"]){self.streamlitTask=[self launchTask:python arguments:@[@"-m",@"streamlit",@"run",@"app.py",@"--server.headless=true",@"--server.port=8501",@"--browser.gatherUsageStats=false"] name:@"Streamlit"];self.ownsStreamlit=self.streamlitTask!=nil;if(!self.streamlitTask){[self showError:@"Lokální server se nepodařilo spustit. Podrobnosti jsou uloženy v Library/Logs/AI Search."];return;}__weak AppDelegate *weakSelf=self;self.streamlitTask.terminationHandler=^(NSTask *task){AppDelegate *strongSelf=weakSelf;if(strongSelf&&![strongSelf serviceReady:@"http://127.0.0.1:8501/_stcore/health"])[strongSelf showError:@"Lokální server se neočekávaně ukončil. Podrobnosti jsou uloženy v Library/Logs/AI Search."];};}else[self log:@"Streamlit již běží; launcher jej nebude spravovat."];while(![self serviceReady:@"http://127.0.0.1:8501/_stcore/health"]){if(self.ownsStreamlit&&!self.streamlitTask.running)return;[NSThread sleepForTimeInterval:.25];}dispatch_async(dispatch_get_main_queue(),^{self.statusLabel.hidden=YES;self.webView.hidden=NO;[self.webView loadRequest:[NSURLRequest requestWithURL:[NSURL URLWithString:@"http://127.0.0.1:8501"]]];[self.window makeKeyAndOrderFront:nil];[NSApp activateIgnoringOtherApps:YES];});}); }
- (void)reloadPage:(id)sender { [self.webView reload]; }
- (void)openSettings:(id)sender { [self.webView evaluateJavaScript:@"Array.from(document.querySelectorAll('button')).find(b => b.innerText.includes('Nastavení'))?.click();" completionHandler:nil]; }
- (void)showHelp:(id)sender { NSAlert *alert=[[NSAlert alloc]init];alert.messageText=@"AI Search";alert.informativeText=@"Vyberte projekt, aktualizujte index a zadejte hledaný výraz nebo otázku. Podrobnosti najdete v README projektu.";[alert runModal]; }
- (BOOL)applicationShouldTerminateAfterLastWindowClosed:(NSApplication *)sender { return YES; }
- (void)windowWillClose:(NSNotification *)notification { [NSApp terminate:nil]; }
- (void)applicationWillTerminate:(NSNotification *)notification { if(self.ownsStreamlit&&self.streamlitTask.running){[self log:@"Ukončuji Streamlit spuštěný touto aplikací."];[self.streamlitTask terminate];}[self.logHandle closeFile]; }
@end
int main(int argc,const char *argv[]){@autoreleasepool{NSApplication *application=[NSApplication sharedApplication];AppDelegate *delegate=[[AppDelegate alloc]init];application.delegate=delegate;application.activationPolicy=NSApplicationActivationPolicyRegular;[application run];}return 0;}
